Organizations:
  - &OrdererOrg
    Name: OrdererMSP
    ID: OrdererMSP
    MSPDir: /var/hyperledger/msp/orderer
  - &Org1
    Name: Org1MSP
    ID: Org1MSP
    MSPDir: /var/hyperledger/msp/org1
    AnchorPeers:
      - Host: peer0-org1
        Port: 7051

Orderer:  
  OrdererType: etcdraft
  Addresses:
    - orderer:7050
  Organizations:
    - *OrdererOrg

Application:
  Organizations:
    - *Org1

Profiles:
  TwoOrgsOrdererGenesis:
    Orderer:
      <<: *Orderer
    Consortiums:
      SampleConsortium:
        Organizations:
          - *Org1
  TwoOrgsChannel:
    Consortium: SampleConsortium
    Application:
      <<: *Application
